### ISSUE TITLE
USB Serial not working with latest version

### ISSUE THREAD

**Issue by racerxdl** [Wiz-IO/wizio-pico#106]
I just did a quick hello world to test using the platform.io and used a hello world example in https://github.com/Wiz-IO/wizio-pico-examples/tree/main/HelloWorld/HELLO but a simpler version:

```c++
#include <Arduino.h>


void setup() {
  Serial.begin(115200, true);
  while(!Serial) {}
  Serial.println("TESTE");
  pinMode(25, OUTPUT);

}

void loop() {
    Serial.print("LO");
    Serial.println("OP");
    // Serial.printf("MILLIS = %u\n", millis());
    printf("PRINTF %f\n", 22.0 / 7);

    static int led = 0;
    digitalWrite(25, led);
    led ^= 1;
    delay(1000);
}
```

The led blinks fine, and the USB port is found (if arduino framework is selected) but nothing goes through the serial port (both with platform.io monitor and screen)

If I compile the same code using the default from platform.io everything works as expected.

My platformio.ini:

"Vanilla" platformio
```
[env:raspberry-pi-pico]
platform = raspberrypi
board = pico
framework = arduino


monitor_port = /dev/ttyACM0
monitor_speed = 115200

; build_flags =
;     -D PICO_STDIO_UART
;     -D PICO_STDIO_USB

; lib_deps = wiring

;lib_deps =
```

Wizio:

```
[env:raspberry-pi-pico]
platform = wizio-pico
board = raspberry-pi-pico
framework = arduino

monitor_port = /dev/ttyACM0
monitor_speed = 115200

; Also tried commenting out, and changing build flags
build_flags =
    -D PICO_STDIO_UART
    -D PICO_STDIO_USB

lib_deps = wiring

;lib_deps =
```

If I change the framework to baremetal, the led also blinks, but no ttyACM port appears (nothing on USB device list). I'm using ubuntu 22.04.

Using Wizio it also does not reset using the USB Port (the "vanilla" works fine)

Build log:

```
Verbose mode can be enabled via `-v, --verbose` option
<<<<<<<<<<<< WIZIO - RASPBERRY PI PICO ( PICOPROBE ) 2021 Georgi Angelov >>>>>>>>>>>>
CONFIGURATION: https://docs.platformio.org/page/boards/wizio-pico/raspberry-pi-pico.html
PLATFORM: WizIO - Raspberry Pi Pico (1.1.0+sha.14314c8) > WizIO - Raspberry Pi Pico ( PICOPROBE )
HARDWARE: RP2040 125MHz, 256KB RAM, 2MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, picoprobe)
PACKAGES: 
 - framework-wizio-pico @ 1.1.0+sha.dbbbdda 
 - tool-wizio-pico @ 1.0.0+sha.3a504e1 
 - toolchain-gccarmnoneeabi @ 1.70201.0 (7.2.1)

ARDUINO RASPBERRYPI PI PICO RP2040 ( PICO - SDK )
  * OPTIMIZATION : -Os
  * STACK        : 2048
  * HEAP         : maximum
  * SPECS        : nano.specs
  * BINARY TYPE  : default ['w25q080', 'memmap_default.ld', '0x10000000']
  * TINYUSB      : DEVICE

LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 17 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
DONE
Checking size .pio/build/raspberry-pi-pico/ARDUINO.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]   5.4% (used 14048 bytes from 262144 bytes)
Flash: [          ]   2.2% (used 46284 bytes from 2097152 bytes)
Configuring upload protocol...
AVAILABLE: cmsis-dap, picoprobe, uf2
CURRENT: upload_protocol = uf2
Uploading...
```

**Comment by Wiz-IO** [comment]
Hi
maybe some is changed in new SDK 1.3.1 ... I not have hardware to test now

but you use normal uart/Serial for printf()
for USB check this
https://github.com/Wiz-IO/framework-wizio-pico/tree/main/arduino/libraries/RP2040/SerialUSB

https://github.com/Wiz-IO/wizio-pico/wiki/ARDUINO#stdio-printf---only-one-driver-will-work

**Comment by Wiz-IO** [comment]
try change SDK version to 1.2.0 ( is backup sdk for platform ) from ini file
this version has been working without problems for the last year

board_build.sdk  = SDK120 // witout this SDK version is 130

and test again...

**Comment by Wiz-IO** [comment]
work...
`
#include <Arduino.h>

void setup()
{
  Serial.begin(115200); // Serial.begin(115200, true); will redirect printf() to this Serial [ uart ] 
  Serial.println("\nArdiuno Raspberrypi PI Pico 2021 Georgi Angelov");
  pinMode(LED, OUTPUT);
}

void loop()
{
  static int led = 0;
  digitalWrite(LED, led);
  led ^= 1;
  delay(1000);
  Serial.println( millis() ); // print to uart
  
  printf("loop"); // build_flags = -D PICO_STDIO_USB ... print to USB virtual port 
}
`
