### ISSUE TITLE
after last update problem with #include "cyw43.h" 

### ISSUE THREAD

**Issue by Squarenix17** [Wiz-IO/wizio-pico#107]
![image](https://user-images.githubusercontent.com/73937907/177374732-b381eda2-1e15-4219-886e-f0ece2d7f676.png)
Hi,
after the last update during the compilation of all projects, even the new ones, I get this error. I have carried out the update procedure that you recommend (delete the data from the .platformio folder)
How can I solve?

**Comment by Wiz-IO** [comment]
yep... will update later
I not have new board for tests and
I need compiler verbose log to look how to construct builder for wifi 

Raspberry Pi support is .... :(
https://github.com/raspberrypi/pico-sdk/issues/897

**Comment by Wiz-IO** [comment]
btw: for pico w select board named **WizIO - Raspberry Pi Pico WiFi ( PICOPROBE ... need SDK 1.4.0 )**
board = **raspberry-pi-pico-w**

and select WiFi arch from INI
build_flags =  **-D PICO_CYW43_ARCH_POLL**

**Comment by Wiz-IO** [comment]
```ini
[env:raspberry-pi-pico-w]
platform = wizio-pico
board = raspberry-pi-pico-w
framework = baremetal
build_flags = 
    -D PICO_STDIO_USB
    -D PICO_CYW43_ARCH_POLL
```

**Comment by Wiz-IO** [comment]
please wait 10-15 mins and reinstall this platform
