### ISSUE TITLE
Update Pico-SDK to latest version

### ISSUE THREAD

**Issue by jonathanlundstrom** [Wiz-IO/wizio-pico#124]
Hi,

There's a new version of the Pico SDK available since about 2 weeks ago. Would you have the time to update this platform to use the latest version? There are many new changes which would be very beneficial to have in this library.

Thank you! ☺️

**Comment by Wiz-IO** [comment]
Hi

I stopped dealing with Raspberry Pi Pico
First, i don't have the new boards to test
and secondly, because of Raspberry Pi's poor attitude towards the project...
