### ISSUE TITLE
USB Flag Causes Build Errors

### ISSUE THREAD

**Issue by Kuroiyatsu** [Wiz-IO/wizio-pico#33]
First, thanks for this awesome work you've done. 

So when I have my platformio.ini file set as below, I receive the following errors when building: 

![image](https://user-images.githubusercontent.com/15186657/111086214-f0abc480-84e8-11eb-92e0-1cf5fe541692.png)

![image](https://user-images.githubusercontent.com/15186657/111086219-015c3a80-84e9-11eb-81ec-ecad4e0e3fed.png)

**Comment by Kuroiyatsu** [comment]
I should also note that when I remove the build flag, the error goes away.

**Comment by Wiz-IO** [comment]
Hi, please re-install platform and test again 
I make changes every day
if error - send me src example for debug

**Comment by Wiz-IO** [comment]
maybe you found bug in the new SDK 1.1.0
these includes is missing
![usb](https://user-images.githubusercontent.com/14574834/111087950-55890e00-852d-11eb-99f4-bf38a83de6f6.jpg)

**Comment by Kuroiyatsu** [comment]
Oh interesting. Yeah I reinstalled and received the same issue. That would make sense now.

**Comment by Wiz-IO** [comment]
and for me give this errors and PC can not install driver

if you have original pico-sdk - please test

**Comment by Kuroiyatsu** [comment]
It looks like I have 1.1.0

**Comment by Wiz-IO** [comment]
usb stdio & sdk 1.0.1 - work for me
switch SDK in ini
`
board_build.sdk = SDK101 ; default is SDK110`

**Comment by Kuroiyatsu** [comment]
That worked for me. 

Thanks again for the hard work!
