### ISSUE TITLE
Debug with picoprobe works, but regular upload does not

### ISSUE THREAD

**Issue by jamon** [Wiz-IO/wizio-pico#81]
I'm able to debug using picoprobe, and the upload works just fine in that case.

However, if I choose to just upload, it says it's going to try to upload via picoprobe, but actually just tries to copy to USB.

platformio.ini:
```
[env:raspberry-pi-pico]
platform = wizio-pico
board = raspberry-pi-pico
framework = baremetal
upload_protocol = picoprobe
debug_tool = picoprobe
```
when uploading:
![image](https://user-images.githubusercontent.com/272949/131224375-a3de1a99-132c-4210-9106-be3dec42f28a.png)
![image](https://user-images.githubusercontent.com/272949/131224411-5275f9dd-2173-4294-bd21-33bc6fea8387.png)

and when debugging (there's more after this, and it starts up and breaks at the first line of main, as it should):
![image](https://user-images.githubusercontent.com/272949/131224456-811ba029-a721-4b73-b0b9-e55b442d7584.png)

It would be very convenient to be able to upload directly using picoprobe all the time, so that you don't have to connect two usb cables up (one to each device).  Am I doing something wrong, or is this just not supported?

**Comment by Wiz-IO** [comment]
upload_protocol = picoprobe
is not soppurted - use default UF2
