### ISSUE TITLE
[example] picoCam

### ISSUE THREAD

**Issue by qrti** [Wiz-IO/wizio-pico#88]
thank you for your work! 
I've used it for a fun project, included are two python scripts to make work easier with pio assembling

[https://github.com/qrti/picoCam](https://github.com/qrti/picoCam)
[https://youtu.be/NsE_c5HfDDw](https://youtu.be/NsE_c5HfDDw)

**Comment by Wiz-IO** [comment]
Nice work ! :+1: 
try color display + camera
https://www.youtube.com/watch?v=Lolq46mt-vY

LCD 
https://github.com/Wiz-IO/framework-wizio-pico/blob/main/library/hal_tft/hal_tft.h#L20
